5_0_A:
	g++ ${CXXFLAGS} -I../lib ../lib/Student_info.cpp ../lib/fails.cpp ../lib/grade.cpp ../lib/median.cpp ../lib/average.cpp 5_0_A_main.cpp -o 5_0_A

5_0_C:
	g++ ${CXXFLAGS} -I../lib ../lib/frame.cpp ../lib/strvect_utils.cpp 5_0_C_main.cpp -o 5_0_C

5_1:
	g++ ${CXXFLAGS} -I../lib ../lib/strvect_utils.cpp 5_1.cpp -o 5_1

5_2:
	g++ ${CXXFLAGS} -I../lib ../lib/Student_info.cpp ../lib/fails.cpp ../lib/grade.cpp ../lib/median.cpp ../lib/average.cpp 5_2_vector.cpp -o 5_2_vector
	g++ ${CXXFLAGS} -I../lib ../lib/Student_info.cpp ../lib/fails.cpp ../lib/grade.cpp ../lib/median.cpp ../lib/average.cpp 5_2_list.cpp -o 5_2_list

5_3:
	g++ ${CXXFLAGS} -I../lib ../lib/Student_info.cpp ../lib/fails.cpp ../lib/grade.cpp ../lib/median.cpp ../lib/average.cpp 5_3.cpp -o 5_3

5_5:
	g++ ${CXXFLAGS} -I../lib ../lib/frame.cpp ../lib/strvect_utils.cpp 5_5.cpp -o 5_5

5_6:
	g++ ${CXXFLAGS} -I../lib ../lib/Student_info.cpp ../lib/fails.cpp ../lib/grade.cpp ../lib/median.cpp ../lib/average.cpp 5_6.cpp -o 5_6

5_9:
	g++ ${CXXFLAGS} 5_9.cpp -o 5_9

5_10:
	g++ ${CXXFLAGS} 5_10.cpp -o 5_10

5_11:
	g++ ${CXXFLAGS} 5_11.cpp -o 5_11

.PHONY:	5_0_A 5_0_C 5_1 5_2 5_3 5_5 5_6 5_9 5_10 5_11 clean

clean:
	rm -f 5_0_A 5_0_C 5_1 5_2 5_3 5_5 5_6 5_9 5_10 5_11

