5_0_A:
	g++ ${CXXFLAGS} -I../lib ../lib/Student_info.cpp ../lib/fails.cpp ../lib/grade.cpp ../lib/median.cpp 5_0_A_main.cpp -o 5_0_A

5_0_C:
	g++ ${CXXFLAGS} -I../lib ../lib/frame.cpp ../lib/strvect_utils.cpp 5_0_C_main.cpp -o 5_0_C

5_2:
	g++ ${CXXFLAGS} -I../lib ../lib/Student_info.cpp ../lib/fails.cpp ../lib/grade.cpp ../lib/median.cpp 5_2_vector.cpp -o 5_2_vector
	g++ ${CXXFLAGS} -I../lib ../lib/Student_info.cpp ../lib/fails.cpp ../lib/grade.cpp ../lib/median.cpp 5_2_list.cpp -o 5_2_list

5_3:
	g++ ${CXXFLAGS} -I../lib ../lib/Student_info.cpp ../lib/fails.cpp ../lib/grade.cpp ../lib/median.cpp 5_3.cpp -o 5_3

5_5:
	g++ ${CXXFLAGS} -I../lib ../lib/frame.cpp ../lib/strvect_utils.cpp 5_5.cpp -o 5_5

5_6:
	g++ ${CXXFLAGS} -I../lib ../lib/Student_info.cpp ../lib/fails.cpp ../lib/grade.cpp ../lib/median.cpp 5_6.cpp -o 5_6


.PHONY:	5_0_A 5_0_C 5_2 5_3 5_5 5_6